---
# Clean up DNS challenges for DNS provider Amazon Route53
- name: Cleaning up challenge DNS entries for domains {{ ', '.join(domains) }}" via Route53
  local_action:
    module: route53
    state: absent
    zone: "{{ item | regex_replace('^(?:.*\\.|)([^.]+\\.[^.]+)$', '\\1') }}"
    record: "{{ item }}"
    type: TXT
    ttl: 60
    value: '"{{ lets_encrypt_challenge.challenge_data.items() | selectattr('1.dns-01.record', 'equalto', item) | map(attribute='1.dns-01.resource_value') | list }}"'
    overwrite: true
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  run_once: True
  with_items: "{{ lets_encrypt_challenge.get('challenge_data', {}).values() | map(attribute='dns-01.record') | unique }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
