---
# Create DNS challenges for DNS provider Google Cloud DNS
- name: Creating challenge DNS entries for domains {{ ', '.join(domains) }}" via Google Cloud DNS
  local_action:
    module: gcdns_record
    state: present
    zone: "{{ item | regex_replace('^(?:.*\\.|)([^.]+\\.[^.]+)$', '\\1') }}"
    record: "{{ item }}"
    type: TXT
    ttl: 300
    value: '"{{ lets_encrypt_challenge.challenge_data.items() | selectattr('1.dns-01.record', 'equalto', item) | map(attribute='1.dns-01.resource_value') | list }}"'
    overwrite: true
    ...
  run_once: True
  with_items: "{{ lets_encrypt_challenge.challenge_data.values() | map(attribute='dns-01.record') | unique }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
