---
# Create DNS challenges for DNS provider HostTech
- name: Creating challenge DNS entries for domains {{ ', '.join(domains) }}" via HostTech API
  local_action:
    module: hosttech_dns
    state: present
    zone: "{{ item | regex_replace('^(?:.*\\.|)([^.]+\\.[^.]+)$', '\\1') }}"
    record: "{{ item }}"
    type: TXT
    ttl: 300
    value: "{{ lets_encrypt_challenge.challenge_data.items() | selectattr('1.dns-01.record', 'equalto', item) | map(attribute='1.dns-01.resource_value') | list }}"
    overwrite: true
    hosttech_username: "{{ hosttech_username }}"
    hosttech_password: "{{ hosttech_password }}"
  run_once: True
  with_items: "{{ lets_encrypt_challenge.challenge_data.values() | map(attribute='dns-01.record') | unique }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
