---
# Create up challenge files directory on server.
- name: Creating challenge destination directory
  become: yes
  file:
    dest: "{{ server_location }}"
    state: directory
    owner: "{{ http_challenge_user }}"
    group: "{{ http_challenge_group }}"
    mode: "{{ http_challenge_folder_mode }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs

# Create challenge files on server.
- name: Copying challenge files for domains {{ ', '.join(domains) }}"
  become: yes
  copy:
    dest: "{{ server_location }}/{{ item.value[challenge].resource[('.well-known/acme-challenge/'|length):] }}"
    content: "{{ item.value[challenge].resource_value }}"
    owner: "{{ http_challenge_user }}"
    group: "{{ http_challenge_group }}"
    mode: "{{ http_challenge_file_mode }}"
  with_dict: "{{ lets_encrypt_challenge.challenge_data }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
