---
# Clean up challenge files on server.
- name: "Cleaning up challenge files for domains {{ ', '.join(domains) }}"
  become: yes
  file:
    path: "{{ server_location }}/{{ item.value[challenge].resource[('.well-known/acme-challenge/'|length):] }}"
    state: absent
  with_dict: "{{ lets_encrypt_challenge.get('challenge_data', {}) }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
