---
- name: Sanity checks
  fail:
    msg: "dns_provider must be defined for dns-01 DNS challenge"
  when: "challenge == 'dns-01' and dns_provider is undefined"

- block:
  - name: "Creating private key for domains {{ ', '.join(domains) }}"
    local_action: command python {{ role_path }}/code/certtool.py gen-key --key "{{ keys_path }}{{ key_name }}.key" --algorithm {{ algorithm }} --key-length {{ key_length }}
    run_once: True
  tags:
  - issue-tls-certs-newkey
  - create-tls-keys

- block:
  - name: "Creating CSR for domains {{ ', '.join(domains) }}"
    local_action: command python {{ role_path }}/code/certtool.py gen-csr --key "{{ keys_path }}{{ key_name }}.key" --csr "{{ keys_path }}{{ key_name }}.csr" --domains "{{ ','.join(domains) }}" {% if ocsp_must_staple %}--must-staple{% endif %}
    run_once: True
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
  - create-tls-keys
  - create-tls-csr

- block:
  - name: "Get root certificate for domains {{ ', '.join(domains) }}"
    local_action:
      module: get_url
      url: "{{ root_certificate }}"
      dest: "{{ keys_path }}{{ key_name }}-root.pem"
    run_once: True

  - name: "Get intermediate certificate for domains {{ ', '.join(domains) }}"
    local_action:
      module: get_url
      url: "{{ intermediate_certificate }}"
      dest: "{{ keys_path }}{{ key_name }}-chain.pem"
    run_once: True

  - name: "Form root chain for domains {{ ', '.join(domains) }}"
    local_action:
      module: copy
      dest: "{{ keys_path }}{{ key_name }}-rootchain.pem"
      content: "{{ lookup('file', keys_path ~ key_name ~ '-root.pem') }}\n{{ lookup('file', keys_path ~ key_name ~ '-chain.pem') }}\n"
    run_once: True
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
  - get-tls-chain

- name: "Preparing challenges for domains {{ ', '.join(domains) }}"
  local_action:
    module: letsencrypt
    account_key: "{{ acme_account }}"
    csr: "{{ keys_path }}{{ key_name }}.csr"
    dest: "{{ keys_path }}{{ key_name }}.pem"
    fullchain_dest: "{{ keys_path }}{{ key_name }}-fullchain.pem"
    account_email: "{{ acme_email }}"
    terms_agreed: "{{ terms_agreed }}"
    challenge: "{{ challenge }}"
    acme_directory: "{{ acme_directory }}"
    acme_version: "{{ acme_version }}"
    remaining_days: 91
  run_once: True
  register: lets_encrypt_challenge
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs

- debug: msg="account URI: {{ lets_encrypt_challenge.account_uri }}; order URI: {{ lets_encrypt_challenge.order_uri }}"
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs

- block:
  # Set up HTTP challenges
  - include_tasks: http-create.yml
    when: "challenge == 'http-01'"

  # Set up DNS challenges
  - include_tasks: dns-{{ dns_provider }}-create.yml
    when: "challenge == 'dns-01'"

  - name: "Getting certificates for domains {{ ', '.join(domains) }}"
    local_action:
      module: letsencrypt
      account_key: "{{ acme_account }}"
      csr: "{{ keys_path }}{{ key_name }}.csr"
      dest: "{{ keys_path }}{{ key_name }}.pem"
      fullchain_dest: "{{ keys_path }}{{ key_name }}-fullchain.pem"
      account_email: "{{ acme_email }}"
      terms_agreed: "{{ terms_agreed }}"
      challenge: "{{ challenge }}"
      acme_directory: "{{ acme_directory }}"
      acme_version: "{{ acme_version }}"
      remaining_days: 91
      data: "{{ lets_encrypt_challenge }}"
    run_once: True

  always:
  # Clean up HTTP challenges
  - include_tasks: http-cleanup.yml
    when: "challenge == 'http-01'"

  # Clean up DNS challenges
  - include_tasks: dns-{{ dns_provider }}-cleanup.yml
    when: "challenge == 'dns-01'"

  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
  when: lets_encrypt_challenge is changed

- name: "Verifying certificate for domains {{ ', '.join(domains) }}"
  local_action:
    module: command
    _raw_params: openssl verify -CAfile "{{ keys_path }}{{ key_name }}-root.pem" -untrusted "{{ keys_path }}{{ key_name }}-chain.pem" "{{ keys_path }}{{ key_name }}.pem"
  changed_when: False
  run_once: True
  tags:
  - issue-tls-certs-newkey
  - issue-tls-certs
  - verify-tls-certs
